import logo from "./logo.png";
import instagram from "./instagram.svg";
import youtube from "./youtube.svg";
import facebook from "./facebook.svg";
import tech from "./tech.png";
import tooth from "./tooth.png";
import dna from "./dna.png";
import img1 from './img1.png';
import img2 from './img2.png';
import img3 from './img3.png';
import img4 from './img4.png';
import img5 from './img5.png';
import img6 from './img6.png';
import img7 from './img7.png';
import img8 from './img8.png';
import img9 from './img9.png';
import img10 from './img10.png';
import img11 from './img11.png';
import img12 from './img12.png';
import menu from './menu.svg';

export { logo, instagram, youtube, facebook, dna, tech, tooth, img1,img2, img3, img4,img5,img6,img7,img8,img9,img10,img11,img12, menu };
